const Employee=[
    {
        id:"100",
        uname:"john",
        age:"30",
        desig:"Developer",
        salary:"35000"
    },
    {
        id:"101",
        uname:"Luke",
        age:"30",
        desig:"tester",
        salary:"35000"
    },
    {
        id:"102",
        uname:"Salim",
        age:"34",
        desig:"Developer",
        salary:"45000"
    },
    {
        id:"103",
        uname:"shibil",
        age:"24",
        desig:"Developer",
        salary:"35000"
    },
]
export default Employee